apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: koro-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: ghcr.io/korohandelsgmbh/coding-test-2025:latest
          ports:
            - containerPort: 80

          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: appdb

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT

            - name: REDIS_HOST
              value: redis
              
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT

            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_ENV

            - name: APP_DEBUG
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_DEBUG

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"